### ISSUE TITLE
Ranking messages

### ISSUE THREAD

**Issue by SXBT69** [nostrdice/nostrdice#63]
I think it would be better if the ranking message from NostrDice Social was sent every 4 or 6 hours.

Plus, the message is currently sent every two hours but the prompt mentions "last 60 minutes".

Another way to improve it would be not to repeat several times the NPUB of the losers, but to mention them only once (I'd get rid of the number of particupants)

**Comment by bonomat** [comment]
> Plus, the message is currently sent every two hours but the prompt mentions "last 60 minutes".

It's posting every 60 minutes if there was a winner in that time period, if there was none, then nothing was posted.
